#!/usr/bin/env python3
"""Generate and validate MCP tool inventory from modules/mcp_server.py.

Parses @mcp.tool-decorated functions and emits tool names/signatures.
Can update or check generated inventory blocks in documentation files.
"""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
from pathlib import Path
import re
import sys
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
SOURCE_FILE = ROOT / "modules" / "mcp_server.py"
BEGIN = "<!-- BEGIN MCP TOOL INVENTORY -->"
END = "<!-- END MCP TOOL INVENTORY -->"


@dataclass(frozen=True)
class ToolSig:
    name: str
    signature: str


def _is_mcp_tool_decorator(dec: ast.expr) -> bool:
    call = dec if isinstance(dec, ast.Call) else None
    if call is None:
        return False
    func = call.func
    return isinstance(func, ast.Attribute) and isinstance(func.value, ast.Name) and func.value.id == "mcp" and func.attr == "tool"


def _arg_repr(arg: ast.arg, default: ast.expr | None) -> str:
    left = arg.arg
    if arg.annotation is not None:
        left += f": {ast.unparse(arg.annotation)}"
    if default is not None:
        left += f" = {ast.unparse(default)}"
    return left


def _signature(node: ast.FunctionDef) -> str:
    parts: list[str] = []
    args = node.args

    posonly = list(args.posonlyargs)
    normal = list(args.args)
    defaults = list(args.defaults)
    default_start = len(posonly) + len(normal) - len(defaults)
    all_pos = posonly + normal

    for idx, arg in enumerate(all_pos):
        default = defaults[idx - default_start] if idx >= default_start else None
        parts.append(_arg_repr(arg, default))
        if posonly and idx == len(posonly) - 1:
            parts.append("/")

    if args.vararg is not None:
        var = "*" + args.vararg.arg
        if args.vararg.annotation is not None:
            var += f": {ast.unparse(args.vararg.annotation)}"
        parts.append(var)
    elif args.kwonlyargs:
        parts.append("*")

    for kwarg, default in zip(args.kwonlyargs, args.kw_defaults):
        parts.append(_arg_repr(kwarg, default))

    if args.kwarg is not None:
        kw = "**" + args.kwarg.arg
        if args.kwarg.annotation is not None:
            kw += f": {ast.unparse(args.kwarg.annotation)}"
        parts.append(kw)

    return f"({', '.join(parts)})"


def extract_tools(source_path: Path = SOURCE_FILE) -> list[ToolSig]:
    tree = ast.parse(source_path.read_text(encoding="utf-8"), filename=str(source_path))
    tools: list[ToolSig] = []
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef):
            continue
        if any(_is_mcp_tool_decorator(dec) for dec in node.decorator_list):
            tools.append(ToolSig(name=node.name, signature=_signature(node)))
    return tools


def render_markdown(tools: Iterable[ToolSig]) -> str:
    tool_list = list(tools)
    lines = [
        BEGIN,
        "_This section is auto-generated by `python scripts/generate_mcp_tool_inventory.py --update-docs AGENTS.md docs/technical/MCP_DEBUGGING_TOOLS.md`. Do not edit manually._",
        "",
        f"Tool count: **{len(tool_list)}**",
        "",
        "| Tool | Signature |",
        "|---|---|",
    ]
    for tool in tool_list:
        sig = tool.signature.replace("|", "\\|")
        lines.append(f"| `{tool.name}` | `{sig}` |")
    lines.append(END)
    return "\n".join(lines)


def replace_or_append_block(text: str, block: str) -> str:
    pattern = re.compile(rf"{re.escape(BEGIN)}.*?{re.escape(END)}", re.DOTALL)
    if pattern.search(text):
        return pattern.sub(block, text)
    suffix = "\n\n" if not text.endswith("\n") else "\n"
    return text + suffix + "## Generated MCP Tool Inventory\n\n" + block + "\n"


def parse_inventory_block(text: str) -> tuple[set[str], int | None]:
    m = re.search(rf"{re.escape(BEGIN)}(.*?){re.escape(END)}", text, flags=re.DOTALL)
    if not m:
        return set(), None
    body = m.group(1)
    names = set(re.findall(r"\| `([a-zA-Z0-9_]+)` \|", body))
    count_match = re.search(r"Tool count:\s*\*\*(\d+)\*\*", body)
    count = int(count_match.group(1)) if count_match else None
    return names, count


def cmd_update_docs(paths: list[Path], block: str) -> int:
    for path in paths:
        old = path.read_text(encoding="utf-8")
        new = replace_or_append_block(old, block)
        if new != old:
            path.write_text(new, encoding="utf-8")
    return 0


def cmd_check_docs(paths: list[Path], tools: list[ToolSig]) -> int:
    expected = {t.name for t in tools}
    failed = False
    for path in paths:
        text = path.read_text(encoding="utf-8")
        found, documented_count = parse_inventory_block(text)
        if not found:
            print(f"ERROR: missing generated inventory block in {path}")
            failed = True
            continue
        if documented_count is None or documented_count != len(expected):
            print(f"ERROR: tool count mismatch in {path}: documented={documented_count} expected={len(expected)}")
            failed = True
        if found != expected:
            missing = sorted(expected - found)
            extra = sorted(found - expected)
            print(f"ERROR: tool inventory mismatch in {path}")
            if missing:
                print(f"  Missing tools: {', '.join(missing)}")
            if extra:
                print(f"  Extra tools: {', '.join(extra)}")
            failed = True
    return 1 if failed else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE_FILE)
    parser.add_argument("--format", choices=["markdown", "names"], default="markdown")
    parser.add_argument("--update-docs", nargs="*", type=Path, default=[])
    parser.add_argument("--check-docs", nargs="*", type=Path, default=[])
    args = parser.parse_args()

    tools = extract_tools(args.source)
    if args.format == "names":
        print("\n".join(t.name for t in tools))
    else:
        print(render_markdown(tools))

    block = render_markdown(tools)
    if args.update_docs:
        return cmd_update_docs(args.update_docs, block)
    if args.check_docs:
        return cmd_check_docs(args.check_docs, tools)
    return 0


if __name__ == "__main__":
    sys.exit(main())
